### ISSUE TITLE
Directly Provide JSON Schema

### ISSUE THREAD

**Issue by raunakdoesdev** [varunshenoy/super-json-mode#10]
We have an application where users supply the JSON schema for use directly. I saw that you convert the Pydantic model to JSON internally. Any thoughts on supporting JSON schema directly instead of JSON models or suggestions for converting json schema strings into the pydantic models? 

Very cool work by the way. Thanks for this effort!

**Comment by varunshenoy** [comment]
You should already be able to pass in a JSON schema instead of a Pydantic object. The examples use Pydantic for ergonomic reasons. Take a look at the `__init__` for the `SchemaBatcher`.
