### ISSUE TITLE
Ollama Integration using single processing at a time

### ISSUE THREAD

**Issue by Namangarg110** [varunshenoy/super-json-mode#9]
Dear @varunshenoy,

I modified code to incorporate Ollama into the SuperJSON. However, It is unable to do batch processing. If you think it would be considerable placeholder until Ollama adds batch processing I can make a PR.

Best,
Naman

**Comment by varunshenoy** [comment]
This is a known issue. I'm going to wait until Ollama or llama-cpp-python natively supports batching before accepting any PRs.
